### ISSUE TITLE
How to subscribe to events without DOM modifications?

### ISSUE THREAD

**Issue by mamciek** [motorcyclejs/dom#72]
How can i subscribe events from some dom elements if I do not want to produce changes in DOM?
How can I achive something like this:

```
function main({DOM}) {
   DOM.select('button').events('click').forEach(e => console.log(e))
   return {}
}

run(main, {DOM: makeDOMDriver('#app')})
```
supposing I have html like:
```
<div id="#app">
  <button>Click</button>
</div>
```

**Comment by TylorS** [comment]
I'm not sure that this is supported by the way things currently work. I'll look into it further.

**Comment by mamciek** [comment]
Thanks for reply. I know that I can subscribe to an events with most.fromEvent and it works but it breaks component isolation

**Comment by TylorS** [comment]
So I was looking into this and it may be possible, but not yet implemented, and I'm not sure that it *should*. Right [here](https://github.com/motorcyclejs/dom/blob/develop/src/makeDOMDriver.js#L67) I use `skip(1)` because the first thing that will be emitted is the `rootElement` supplied to `makeDOMDriver()`. 

I do this for 2 reasons. The first being less important, to me, than the second 

1. It would force the map() underneath to check for Element and return appropriately
2. It would be confusing to have event listeners attached before ever creating a DOM structure.

I'm open to ideas as to why making the changes required would be a *good* idea, but for now I don't think it makes much sense. I don't see much use of a DOM driver without using it to modify the DOM.

**Comment by TylorS** [comment]
Closing this as I don't believe currently believe this is something I want to support, buf if you feel the need to reopen for more discussion please feel free.
